apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: external-api=ghcr.io/szma5a/hoge
    argocd-image-updater.argoproj.io/external-api.update-strategy: latest
    argocd-image-updater.argoproj.io/git-branch: :updater-pr-test
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/sZma5a/hoge.git
    path: ./deployment
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: test-project
  syncPolicy:
    automated: {}