apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/sZma5a/hoge.git
    path: ./deployment
    targetRevision: refs/tags/*
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: test-project
  syncPolicy:
    automated: {}