apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hoge-app-dev
  namespace: default
  # annotations:
  #   argocd-image-updater.argoproj.io/write-back-method: argocd
  #   argocd-image-updater.argoproj.io/image-list: target=asia.gcr.io/hoge/fuga/testt:latest
  #   argocdimage-updater.argoproj.io/target.update-strategy: digest
  #   argocd-image-updater.argoproj.io/target.force-update: "true"

spec:
  source:
    repoURL: https://github.com/sZma5a/hoge.git
    path: ./
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: argocd