apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: default
spec:
  source:
    repoURL: https://github.com/sZma5a/hoge.git
    path: ./argocd
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: test-project
  syncPolicy:
    automated: {}