apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: default
  # annotations:
  #   argocd-image-updater.argoproj.io/write-back-method: argocd
  #   argocd-image-updater.argoproj.io/image-list: external-api=ghcr.io/szma5a/hoge/fuga
  #   argocd-image-updater.argoproj.io/external-api.update-strategy: digest

spec:
  source:
    repoURL: https://github.com/sZma5a/hoge.git
    path: ./argocd
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: test-project
  syncPolicy:
    automated: {}