apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-project
  namespace: default
spec:
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
      name: argocd-clustre