apiVersion: v1
kind: Secret
metadata:
  name: argocd-test-repo-secret
  namespace: default
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: test-repository
  project: test-project
  type: git
  url: https://github.com/sZma5a/hoge.git